/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentRouteImport } from './routes/content'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as AuthorTemplateIdRouteImport } from './routes/author.$templateId'
import { Route as PublicationsTemplateIdRouteImport } from './routes/publications.$templateId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorTemplateIdRoute = AuthorTemplateIdRouteImport.update({
  id: '/author/$templateId',
  path: '/author/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsTemplateIdRoute = PublicationsTemplateIdRouteImport.update({
  id: '/publications/$templateId',
  path: '/publications/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/tutorial': typeof TutorialRoute
  '/author/$templateId': typeof AuthorTemplateIdRoute
  '/publications/$templateId': typeof PublicationsTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/tutorial': typeof TutorialRoute
  '/author/$templateId': typeof AuthorTemplateIdRoute
  '/publications/$templateId': typeof PublicationsTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/tutorial': typeof TutorialRoute
  '/author/$templateId': typeof AuthorTemplateIdRoute
  '/publications/$templateId': typeof PublicationsTemplateIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/tutorial'
    | '/author/$templateId'
    | '/publications/$templateId'
    | '/templates/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/tutorial'
    | '/author/$templateId'
    | '/publications/$templateId'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/tutorial'
    | '/author/$templateId'
    | '/publications/$templateId'
    | '/templates/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRoute
  TutorialRoute: typeof TutorialRoute
  AuthorTemplateIdRoute: typeof AuthorTemplateIdRoute
  PublicationsTemplateIdRoute: typeof PublicationsTemplateIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$templateId': {
      id: '/author/$templateId'
      path: '/author/$templateId'
      fullPath: '/author/$templateId'
      preLoaderRoute: typeof AuthorTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$templateId': {
      id: '/publications/$templateId'
      path: '/publications/$templateId'
      fullPath: '/publications/$templateId'
      preLoaderRoute: typeof PublicationsTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRoute,
  TutorialRoute: TutorialRoute,
  AuthorTemplateIdRoute: AuthorTemplateIdRoute,
  PublicationsTemplateIdRoute: PublicationsTemplateIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
